name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write  # For trusted publishing to PyPI
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install UV
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"
    
    - name: Set up Python
      run: uv python install 3.11
    
    - name: Install dependencies
      run: uv sync --dev
    
    - name: Run tests
      run: python scripts/run_tests.py
    
    - name: Build package
      run: uv build
    
    - name: Validate build
      run: python scripts/check_build.py
    
    - name: Extract version from tag
      id: extract_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ steps.extract_version.outputs.VERSION }}
        body: |
          ## LangExtract Azure OpenAI Provider v${{ steps.extract_version.outputs.VERSION }}
          
          ### Installation
          ```bash
          uv add langextract-azureopenai==${{ steps.extract_version.outputs.VERSION }}
          # or
          pip install langextract-azureopenai==${{ steps.extract_version.outputs.VERSION }}
          ```
          
          ### What's Changed
          - See [CHANGELOG.md](https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md) for details
        files: dist/*
        draft: false
        prerelease: false
    
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        # Uses OIDC trusted publishing, no token needed
        # Configure at: https://pypi.org/manage/account/publishing/
        repository-url: https://upload.pypi.org/legacy/